/**
 * Seed curated Delhi restaurants from data/restaurants.json into Supabase.
 *
 * Prerequisites:
 *   - Run migrations: `supabase db push` (remote) or `supabase db reset` (local)
 *   - Migration 002_seed_helpers.sql defines `upsert_restaurant_with_tags`
 *
 * --- Option A: Generate SQL file (no API key) ---
 *   npx tsx scripts/seed-restaurants.ts --sql > supabase/seed.sql
 *   psql "$DATABASE_URL" -f supabase/seed.sql
 *
 * --- Option B: Upsert via Supabase API (service role) ---
 *   export SUPABASE_URL="https://<project-ref>.supabase.co"
 *   export SUPABASE_SERVICE_ROLE_KEY="<service-role-secret>"
 *   npx tsx scripts/seed-restaurants.ts
 *
 * --- Local Supabase ---
 *   supabase start
 *   export SUPABASE_URL="http://127.0.0.1:54321"
 *   export SUPABASE_SERVICE_ROLE_KEY="$(supabase status -o env | grep SERVICE_ROLE_KEY | cut -d= -f2-)"
 *   npx tsx scripts/seed-restaurants.ts
 *
 * Never commit the service role key. Use CI secrets or local env only.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_PATH = join(__dirname, '..', 'data', 'restaurants.json');

type TagRow = { tag_type: 'vibe' | 'occasion' | 'food'; tag: string };

type RestaurantSeed = {
  name: string;
  slug: string;
  cuisine: string;
  price_band: number;
  area: 'north' | 'south' | 'east' | 'west';
  neighbourhood: string;
  lat: number;
  lng: number;
  description: string;
  image_urls: string[];
  is_editors_pick: boolean;
  tags: TagRow[];
};

function loadRestaurants(): RestaurantSeed[] {
  const raw = readFileSync(DATA_PATH, 'utf8');
  return JSON.parse(raw) as RestaurantSeed[];
}

function sqlLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlArray(values: string[]): string {
  if (values.length === 0) return 'ARRAY[]::text[]';
  return `ARRAY[${values.map(sqlLiteral).join(', ')}]::text[]`;
}

function sqlTags(tags: TagRow[]): string {
  const rows = tags.map(
    (t) =>
      `jsonb_build_object('tag_type', ${sqlLiteral(t.tag_type)}, 'tag', ${sqlLiteral(t.tag)})`
  );
  return `jsonb_build_array(${rows.join(', ')})`;
}

function emitSql(restaurants: RestaurantSeed[]): string {
  const lines: string[] = [
    '-- Generated by scripts/seed-restaurants.ts --sql',
    'BEGIN;',
  ];

  for (const r of restaurants) {
    lines.push(
      `SELECT upsert_restaurant_with_tags(` +
        `${sqlLiteral(r.slug)}, ` +
        `${sqlLiteral(r.name)}, ` +
        `${sqlLiteral(r.cuisine)}, ` +
        `${r.price_band}, ` +
        `${sqlLiteral(r.area)}::delhi_area, ` +
        `${sqlLiteral(r.neighbourhood)}, ` +
        `${r.lat}, ` +
        `${r.lng}, ` +
        `${sqlLiteral(r.description)}, ` +
        `${sqlArray(r.image_urls)}, ` +
        `${r.is_editors_pick}, ` +
        `${sqlTags(r.tags)}` +
        `);`
    );
  }

  lines.push('COMMIT;', '');
  return lines.join('\n');
}

async function seedViaApi(restaurants: RestaurantSeed[]): Promise<void> {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    console.error(
      'Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY. Use --sql or set env vars.'
    );
    process.exit(1);
  }

  const { createClient } = await import('@supabase/supabase-js');
  const supabase = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  let ok = 0;
  for (const r of restaurants) {
    const { error } = await supabase.rpc('upsert_restaurant_with_tags', {
      p_slug: r.slug,
      p_name: r.name,
      p_cuisine: r.cuisine,
      p_price_band: r.price_band,
      p_area: r.area,
      p_neighbourhood: r.neighbourhood,
      p_lat: r.lat,
      p_lng: r.lng,
      p_description: r.description,
      p_image_urls: r.image_urls,
      p_is_editors_pick: r.is_editors_pick,
      p_tags: r.tags,
    });

    if (error) {
      console.error(`Failed ${r.slug}:`, error.message);
      process.exitCode = 1;
    } else {
      ok += 1;
      if (ok % 10 === 0) console.log(`Seeded ${ok}/${restaurants.length}...`);
    }
  }

  console.log(`Done. Upserted ${ok} restaurants.`);
}

async function main(): Promise<void> {
  const restaurants = loadRestaurants();
  const sqlMode = process.argv.includes('--sql');

  if (sqlMode) {
    process.stdout.write(emitSql(restaurants));
    return;
  }

  await seedViaApi(restaurants);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
